### ISSUE TITLE
Timeline exploration

### ISSUE THREAD

**Issue by ceenell** [USGS-VIZLAB/drought-timeline#6]
- [x] Using fixed and variable thresholds
- [x] Use CASC regions to visualize regional patterns
- [x] Using different % thresholds - try all thresholds using color to encode the %

The purpose is to get a quick look at the chart with different facets of the drought properties data. The styling does not need to be perfect, but should be consistent across charts to allow us to easily compare them and make decisions on the next steps as well as see broad patterns across the approaches

**Comment by ceenell** [comment]
Migrated this from https://github.com/USGS-VIZLAB/what-is-drought/issues/19

I believe some of this has been accomplished, please document here @hcorson-dosch

**Comment by hcorson-dosch** [comment]
See also the Design Studio mural, where these variations were discussed.

# Fixed vs variable thresholds

Fixed - 2% - National - 1951-2020
![swarm_site_2](https://user-images.githubusercontent.com/54007288/187267812-adc0bfc8-a986-4355-8f91-b24f18a65acc.png)

Variable - jd7d - 2% - National - 1951-2020
![swarm_national](https://user-images.githubusercontent.com/54007288/187267765-27cb84f8-3a92-4038-a440-a23a44ff7a83.png)

# CASC regions
Shows clear discrepancies in # of gages per region, as well as very different patterns in different CASC regions

### Fixed - 2% - 1951-2020
Midwest:
![swarm_site_2_MW](https://user-images.githubusercontent.com/54007288/187268336-1a45dd37-38e9-41df-a39f-a475415b5cff.png)

North central:
![swarm_site_2_NC](https://user-images.githubusercontent.com/54007288/187268351-679a2e8d-c05b-4c79-b2b9-f034035c9026.png)

Northeast:
![swarm_site_2_NE](https://user-images.githubusercontent.com/54007288/187268366-f91ea752-b65e-456f-b995-54b4488ce0cf.png)

Northwest:
![swarm_site_2_NW](https://user-images.githubusercontent.com/54007288/187268384-502ba78a-8b77-40ee-b513-bb822e3e859c.png)

South central:
![swarm_site_2_SC](https://user-images.githubusercontent.com/54007288/187268401-e1cc70b8-b977-4529-8820-c999db06a792.png)

Southeast:
![swarm_site_2_SE](https://user-images.githubusercontent.com/54007288/187268420-e74ed0d3-9ed4-49e0-93b1-c13391cab2f3.png)

Southwest:
![swarm_site_2_SW](https://user-images.githubusercontent.com/54007288/187268436-3f87883e-a4aa-46fb-9f9f-bbb3e2413343.png)

# Different % thresholds
### Variable - jd7d - 1951-1952
2%
![swarm_site_2_1951_1952](https://user-images.githubusercontent.com/54007288/187268865-5dc5f6c3-f1e0-47d1-ad9a-d042677c68ff.png)

5%
![swarm_jd7d_5_1951_1952](https://user-images.githubusercontent.com/54007288/187268872-7ab19ead-d91d-4229-9a7c-1e9eb888e540.png)

10%
![swarm_jd7d_10_1951_1952](https://user-images.githubusercontent.com/54007288/187268888-1cb611d9-37c9-4f46-b913-8bb5161343d7.png)

20%
![swarm_jd7d_20_1951_1952](https://user-images.githubusercontent.com/54007288/187268901-4fc5ba3d-bcda-4a80-9aeb-061582f7ccb6.png)

30%
![swarm_jd7d_30_1951_1952](https://user-images.githubusercontent.com/54007288/187268911-49f58a18-6572-4360-889f-4be853ce6a01.png)

**Comment by hcorson-dosch** [comment]
Initial exploration work done, so closing this issue
