### ISSUE TITLE
work on data processing steps for swarm positioning

### ISSUE THREAD

**Issue by ceenell** [USGS-VIZLAB/drought-timeline#7]
Spend a short amount of time looking for obvious ways to speed up the data processing steps for that chart. This will make developing those charts much faster.

Notes:
- time intensive to find positions in swarm. currently takes 18 min to process the smallest chunk - 2% for 20 years
- chunking by time needs to be done thoughtfully to ensure that events crossing time breaks are included in full duration
- `create_event_swarm` fxn may be worth exploring

**Comment by ceenell** [comment]
Migrated from https://github.com/USGS-VIZLAB/what-is-drought/issues/20

@hcorson-dosch  what is the status of this issue?

**Comment by hcorson-dosch** [comment]
This work was done initially in `what-is-drought`. I copied it over to this new repo the end of last week, but deprioritized PRing in favor of continuing the planned exploratory work, since you weren't going to be available to review. I can get a PR up today.

**Comment by ceenell** [comment]
That is fine. I know that you have made progress on this and I did not see any associated PRs with this issue in the other repo, so this is a friendly nudge to document the work that has been accomplished.
